import type { Metadata } from 'next';
import { MenuLink, MenuListProps, FeatureCardProp, FeatureCardsProps } from '@/types';
import { MenuList } from '@/components/ui';
import { Geist, Geist_Mono } from 'next/font/google';
import { Averia_Serif_Libre } from 'next/font/google';
import { Zilla_Slab } from 'next/font/google';
import { useState, useEffect } from 'react';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import './globals.css';

const categoryItems = [
  { label: "Gift for Chrismas", href: "/" },
  { label: "Greek Mythology", href: "/" }
];
const aSLibre = Averia_Serif_Libre({
  weight: ["300","400","700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-title",
})
const ziliaSlab = Zilla_Slab({
  weight: ["300","400","500","600","700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-context",
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <body
        className={`${aSLibre.variable} ${ziliaSlab.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
