import type { Metadata } from 'next';
import { Geist_Mono } from 'next/font/google';
import { Averia_Serif_Libre } from 'next/font/google';
import { Zilla_Slab } from 'next/font/google';
import './globals.css';
import SessionProvider from '@/components/providers/SessionProvider';
import { ShoppingBagProvider } from '@/components/providers/ShoppingBagProvider';
import { auth } from '@/auth';

const aSLibre = Averia_Serif_Libre({
  weight: ["300","400","700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-title",
})

const ziliaSlab = Zilla_Slab({
  weight: ["300","400","500","600","700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-context",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${aSLibre.variable} ${ziliaSlab.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ShoppingBagProvider>
            {children}
          </ShoppingBagProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
